import{a as p,S as L,i as c}from"./assets/vendor-DoGir2lE.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&u(f)}).observe(document,{childList:!0,subtree:!0});function d(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=d(t);fetch(t.href,r)}})();const w="https://pixabay.com",v="/api/",b="53336215-c76f1a14c7207891fbb20a22b";async function S(e,o){const d=`${w}${v}`;return(await p.get(d,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o}})).data}const m=document.querySelector(".gallery"),a=document.querySelector(".js-load-btn");function E(e){return`<li class='gallery-item'>
    <a class='gallery-link' href=${e.largeImageURL}>
    <img loading='lazy' class='gallery-image' src='${e.webformatURL}' alt='${e.tags}'/>
    <div class='img'>
    <p><strong>Likes</strong> ${e.likes}</p>
    <p><strong>Views</strong> ${e.views}</p>
    <p><strong>Comments</strong> ${e.comments}</p>
    <p><strong>Downloads</strong> ${e.downloads}</p></div></a></li>`}function P(e){const o=e.map(E).join("");m.insertAdjacentHTML("beforeend",o)}function B(){m.innerHTML=""}function I(){const e=document.getElementById("loader-overlay");e&&e.classList.remove("hidden")}function i(){const e=document.getElementById("loader-overlay");e&&e.classList.add("hidden")}function O(){a&&a.classList.remove("hidden")}function n(){a&&a.classList.add("hidden")}let $=new L(".gallery a",{captionsData:"alt",captionDelay:250,close:!0,docClose:!1});const g=document.querySelector(".form"),q=15;let l,s,y;n();i();g.addEventListener("submit",async e=>{if(e.preventDefault(),l=new FormData(e.target).get("search-text").trim(),s=1,!l||l.length===0){c.warning({title:"Warning",message:"Please enter a search term!"});return}n(),B(),await h()});a.addEventListener("click",async()=>{s+=1,await h()});async function h(){try{I();const e=await S(l,s);if(y=Math.ceil(e.total/q),D(),e.hits.length===0){c.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}),n(),i(),g.reset();return}P(e.hits),s>1&&M(),$.refresh()}catch(e){c.error({title:"Error",message:"Something went wrong. Please try again later."}),n(),i(),g.reset(),console.error(e)}finally{i()}}function D(){s<y?O():(n(),c.info({title:"The End",message:"We`re sorry, but you`ve reached the end of search results."}))}function M(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
