import{a as L,S as w,i as l}from"./assets/vendor-LvtvrCkc.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const g of r.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&f(g)}).observe(document,{childList:!0,subtree:!0});function u(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function f(t){if(t.ep)return;t.ep=!0;const r=u(t);fetch(t.href,r)}})();const v="https://pixabay.com",b="/api/",S="53336215-c76f1a14c7207891fbb20a22b";async function E(e,o){const u=`${v}${b}`;return(await L.get(u,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o}})).data}let P=new w(".gallery a",{captionsData:"alt",captionDelay:250,close:!0,docClose:!1});const m=document.querySelector(".gallery"),a=document.querySelector(".js-load-btn");function B(e){return`<li class='gallery-item'>
    <a class='gallery-link' href=${e.largeImageURL}>
    <img loading='lazy' class='gallery-image' src='${e.webformatURL}' alt='${e.tags}'/>
    <div class='img'>
    <p><strong>Likes</strong> ${e.likes}</p>
    <p><strong>Views</strong> ${e.views}</p>
    <p><strong>Comments</strong> ${e.comments}</p>
    <p><strong>Downloads</strong> ${e.downloads}</p></div></a></li>`}function I(e){const o=e.map(B).join("");m.insertAdjacentHTML("beforeend",o),P.refresh()}function O(){m.innerHTML=""}function y(){const e=document.getElementById("loader-overlay");e&&e.classList.remove("hidden")}function s(){const e=document.getElementById("loader-overlay");e&&e.classList.add("hidden")}function $(){a&&a.classList.remove("hidden")}function n(){a&&a.classList.add("hidden")}const c=document.querySelector(".form"),q=c.elements["search-text"],D=15;let i,d,h;n();s();c.addEventListener("submit",async e=>{if(e.preventDefault(),i=new FormData(e.target).get("search-text").trim(),d=1,!i||i.length===0){l.warning({title:"Warning",message:"Please enter a search term!"});return}y(),n(),O(),await p()});a.addEventListener("click",async()=>{d+=1,await p()});async function p(){try{y();const e=await E(i,d);if(h=Math.ceil(e.total/D),e.hits.length===0){l.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}),n(),s(),c.reset();return}I(e.hits),q.value="",M()}catch(e){l.error({title:"Error",message:"Something went wrong. Please try again later."}),n(),s(),c.reset(),console.error(e)}finally{s()}}function M(){d<h?($(),N()):(n(),l.info({title:"The End",message:"We`re sorry, but you`ve reached the end of search results."}))}function N(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
