import{a as f,S as m,i as c}from"./assets/vendor-LvtvrCkc.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();async function g(e){return(await f.get("https://pixabay.com/api/",{params:{key:"53336215-c76f1a14c7207891fbb20a22b",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true"}})).data}let y=new m(".gallery a",{captionsData:"alt",captionDelay:250,close:!0,docClose:!1});const u=document.querySelector(".gallery");function p(e){return`<li class='gallery-item'>
    <a class='gallery-link' href=${e.largeImageURL}>
    <img class='gallery-image' src='${e.webformatURL}' alt='${e.tags}'/>
    <div class='img'>
    <p><strong>Likes</strong> ${e.likes}</p>
    <p><strong>Views</strong> ${e.views}</p>
    <p><strong>Comments</strong> ${e.comments}</p>
    <p><strong>Downloads</strong> ${e.downloads}</p></div></a></li>`}function h(e){const r=e.map(p).join("");return u.insertAdjacentHTML("beforeend",r),y.refresh(),r}function L(){u.innerHTML=""}function v(){const e=document.getElementById("loader-overlay");e&&e.classList.remove("hidden")}function n(){const e=document.getElementById("loader-overlay");e&&e.classList.add("hidden")}function w(){const e=document.querySelector(".js-load-btn");e&&e.classList.remove("hidden")}function a(){const e=document.querySelector(".js-load-btn");e&&e.classList.add("hidden")}const i=document.querySelector(".form"),b=i.elements["search-text"];a();n();i.addEventListener("submit",async e=>{e.preventDefault();const r=e.target.elements["search-text"].value.trim();if(r.length!==0){if(!r){c.warning({title:"Warning",message:"Please enter a search term!"});return}v(),a(),L();try{const s=await g(r);if(w(),s.hits.length===0){c.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}),a(),n(),i.reset();return}h(s.hits),b.value=""}catch(s){c.error({title:"Error",message:"Something went wrong. Please try again later."}),a(),n(),i.reset(),console.error(s)}n()}});
//# sourceMappingURL=index.js.map
